# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/nikepupu/10D6122F101EC956/232B

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/nikepupu/10D6122F101EC956/232B

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/nikepupu/10D6122F101EC956/232B/CMakeFiles /media/nikepupu/10D6122F101EC956/232B/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/nikepupu/10D6122F101EC956/232B/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named res

# Build rule for target.
res: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 res
.PHONY : res

# fast build rule for target.
res/fast:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/build
.PHONY : res/fast

detector.o: detector.cpp.o

.PHONY : detector.o

# target to build an object file
detector.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/detector.cpp.o
.PHONY : detector.cpp.o

detector.i: detector.cpp.i

.PHONY : detector.i

# target to preprocess a source file
detector.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/detector.cpp.i
.PHONY : detector.cpp.i

detector.s: detector.cpp.s

.PHONY : detector.s

# target to generate assembly for a file
detector.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/detector.cpp.s
.PHONY : detector.cpp.s

exponential_model.o: exponential_model.cpp.o

.PHONY : exponential_model.o

# target to build an object file
exponential_model.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/exponential_model.cpp.o
.PHONY : exponential_model.cpp.o

exponential_model.i: exponential_model.cpp.i

.PHONY : exponential_model.i

# target to preprocess a source file
exponential_model.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/exponential_model.cpp.i
.PHONY : exponential_model.cpp.i

exponential_model.s: exponential_model.cpp.s

.PHONY : exponential_model.s

# target to generate assembly for a file
exponential_model.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/exponential_model.cpp.s
.PHONY : exponential_model.cpp.s

filter.o: filter.cpp.o

.PHONY : filter.o

# target to build an object file
filter.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/filter.cpp.o
.PHONY : filter.cpp.o

filter.i: filter.cpp.i

.PHONY : filter.i

# target to preprocess a source file
filter.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/filter.cpp.i
.PHONY : filter.cpp.i

filter.s: filter.cpp.s

.PHONY : filter.s

# target to generate assembly for a file
filter.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/filter.cpp.s
.PHONY : filter.cpp.s

layers/layer1.o: layers/layer1.cpp.o

.PHONY : layers/layer1.o

# target to build an object file
layers/layer1.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer1.cpp.o
.PHONY : layers/layer1.cpp.o

layers/layer1.i: layers/layer1.cpp.i

.PHONY : layers/layer1.i

# target to preprocess a source file
layers/layer1.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer1.cpp.i
.PHONY : layers/layer1.cpp.i

layers/layer1.s: layers/layer1.cpp.s

.PHONY : layers/layer1.s

# target to generate assembly for a file
layers/layer1.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer1.cpp.s
.PHONY : layers/layer1.cpp.s

layers/layer2.o: layers/layer2.cpp.o

.PHONY : layers/layer2.o

# target to build an object file
layers/layer2.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer2.cpp.o
.PHONY : layers/layer2.cpp.o

layers/layer2.i: layers/layer2.cpp.i

.PHONY : layers/layer2.i

# target to preprocess a source file
layers/layer2.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer2.cpp.i
.PHONY : layers/layer2.cpp.i

layers/layer2.s: layers/layer2.cpp.s

.PHONY : layers/layer2.s

# target to generate assembly for a file
layers/layer2.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer2.cpp.s
.PHONY : layers/layer2.cpp.s

layers/layer3.o: layers/layer3.cpp.o

.PHONY : layers/layer3.o

# target to build an object file
layers/layer3.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer3.cpp.o
.PHONY : layers/layer3.cpp.o

layers/layer3.i: layers/layer3.cpp.i

.PHONY : layers/layer3.i

# target to preprocess a source file
layers/layer3.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer3.cpp.i
.PHONY : layers/layer3.cpp.i

layers/layer3.s: layers/layer3.cpp.s

.PHONY : layers/layer3.s

# target to generate assembly for a file
layers/layer3.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/layers/layer3.cpp.s
.PHONY : layers/layer3.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/main.cpp.s
.PHONY : main.cpp.s

misc.o: misc.cpp.o

.PHONY : misc.o

# target to build an object file
misc.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/misc.cpp.o
.PHONY : misc.cpp.o

misc.i: misc.cpp.i

.PHONY : misc.i

# target to preprocess a source file
misc.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/misc.cpp.i
.PHONY : misc.cpp.i

misc.s: misc.cpp.s

.PHONY : misc.s

# target to generate assembly for a file
misc.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/misc.cpp.s
.PHONY : misc.cpp.s

saot_config.o: saot_config.cpp.o

.PHONY : saot_config.o

# target to build an object file
saot_config.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/saot_config.cpp.o
.PHONY : saot_config.cpp.o

saot_config.i: saot_config.cpp.i

.PHONY : saot_config.i

# target to preprocess a source file
saot_config.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/saot_config.cpp.i
.PHONY : saot_config.cpp.i

saot_config.s: saot_config.cpp.s

.PHONY : saot_config.s

# target to generate assembly for a file
saot_config.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/saot_config.cpp.s
.PHONY : saot_config.cpp.s

saot_inference_Config.o: saot_inference_Config.cpp.o

.PHONY : saot_inference_Config.o

# target to build an object file
saot_inference_Config.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/saot_inference_Config.cpp.o
.PHONY : saot_inference_Config.cpp.o

saot_inference_Config.i: saot_inference_Config.cpp.i

.PHONY : saot_inference_Config.i

# target to preprocess a source file
saot_inference_Config.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/saot_inference_Config.cpp.i
.PHONY : saot_inference_Config.cpp.i

saot_inference_Config.s: saot_inference_Config.cpp.s

.PHONY : saot_inference_Config.s

# target to generate assembly for a file
saot_inference_Config.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/saot_inference_Config.cpp.s
.PHONY : saot_inference_Config.cpp.s

template.o: template.cpp.o

.PHONY : template.o

# target to build an object file
template.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/template.cpp.o
.PHONY : template.cpp.o

template.i: template.cpp.i

.PHONY : template.i

# target to preprocess a source file
template.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/template.cpp.i
.PHONY : template.cpp.i

template.s: template.cpp.s

.PHONY : template.s

# target to generate assembly for a file
template.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/template.cpp.s
.PHONY : template.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/test.cpp.s
.PHONY : test.cpp.s

util/file_util.o: util/file_util.cpp.o

.PHONY : util/file_util.o

# target to build an object file
util/file_util.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/util/file_util.cpp.o
.PHONY : util/file_util.cpp.o

util/file_util.i: util/file_util.cpp.i

.PHONY : util/file_util.i

# target to preprocess a source file
util/file_util.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/util/file_util.cpp.i
.PHONY : util/file_util.cpp.i

util/file_util.s: util/file_util.cpp.s

.PHONY : util/file_util.s

# target to generate assembly for a file
util/file_util.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/util/file_util.cpp.s
.PHONY : util/file_util.cpp.s

util/mat_util.o: util/mat_util.cpp.o

.PHONY : util/mat_util.o

# target to build an object file
util/mat_util.cpp.o:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/util/mat_util.cpp.o
.PHONY : util/mat_util.cpp.o

util/mat_util.i: util/mat_util.cpp.i

.PHONY : util/mat_util.i

# target to preprocess a source file
util/mat_util.cpp.i:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/util/mat_util.cpp.i
.PHONY : util/mat_util.cpp.i

util/mat_util.s: util/mat_util.cpp.s

.PHONY : util/mat_util.s

# target to generate assembly for a file
util/mat_util.cpp.s:
	$(MAKE) -f CMakeFiles/res.dir/build.make CMakeFiles/res.dir/util/mat_util.cpp.s
.PHONY : util/mat_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... res"
	@echo "... rebuild_cache"
	@echo "... detector.o"
	@echo "... detector.i"
	@echo "... detector.s"
	@echo "... exponential_model.o"
	@echo "... exponential_model.i"
	@echo "... exponential_model.s"
	@echo "... filter.o"
	@echo "... filter.i"
	@echo "... filter.s"
	@echo "... layers/layer1.o"
	@echo "... layers/layer1.i"
	@echo "... layers/layer1.s"
	@echo "... layers/layer2.o"
	@echo "... layers/layer2.i"
	@echo "... layers/layer2.s"
	@echo "... layers/layer3.o"
	@echo "... layers/layer3.i"
	@echo "... layers/layer3.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... misc.o"
	@echo "... misc.i"
	@echo "... misc.s"
	@echo "... saot_config.o"
	@echo "... saot_config.i"
	@echo "... saot_config.s"
	@echo "... saot_inference_Config.o"
	@echo "... saot_inference_Config.i"
	@echo "... saot_inference_Config.s"
	@echo "... template.o"
	@echo "... template.i"
	@echo "... template.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... util/file_util.o"
	@echo "... util/file_util.i"
	@echo "... util/file_util.s"
	@echo "... util/mat_util.o"
	@echo "... util/mat_util.i"
	@echo "... util/mat_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

